name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "requirements*.txt"

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt
        uv pip install ruff mypy pytest pytest-cov

    - name: Run ruff linting
      run: |
        source .venv/bin/activate
        ruff check .

    - name: Run ruff formatting check
      run: |
        source .venv/bin/activate
        ruff format --check .

    - name: Run mypy type checking
      run: |
        source .venv/bin/activate
        mypy . --strict

    - name: Run tests with pytest
      run: |
        source .venv/bin/activate
        pytest -q --tb=short

    - name: Generate test coverage report
      if: matrix.python-version == '3.11'
      run: |
        source .venv/bin/activate
        pytest --cov=app --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
